mybatis:
  mapper-locations: classpath:mapper/*.xml

#session的有效时间
server:
  port: 8080
  servlet:
    session:
      timeout: 10m
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL57Dialect


jwt:
  config:
    secret: haha  # 加密的secret
    ttl: 365*6000  # token超时时间 秒
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

